#!/usr/bin/env bash
#
# Bring the local LeadAce stack up inside a Claude Code cloud session.
#
# The VM arrives provisioned by scripts/cloud-setup.sh but idle: a snapshot
# keeps files, not processes, and .dev.vars / frontend/.env are gitignored so
# they are never in the clone. This script closes that gap, and is idempotent —
# rerun it after any restart:
#
#   dockerd -> supabase start -> backend/.dev.vars + frontend/.env from
#   `supabase status` -> npm ci -> migrations -> master-document seed ->
#   a confirmed dev user, whose tenant the e2e suites mint JWTs against.
#
# Usage (inside a cloud session):
#   ./scripts/cloud-bootstrap.sh
#   nohup make dev >/tmp/leadace-dev.log 2>&1 &     # API :8787, MCP :8788, frontend :5273
#   ./e2e/regression-all.sh
#
# Env:
#   LEADACE_CLOUD_FORCE=1   run outside a cloud session (it writes env files)
#   LEADACE_CLOUD_REGEN=1   rewrite backend/.dev.vars and frontend/.env even
#                           when they already exist
#   LEADACE_DEV_EMAIL=...   dev user to provision (default dev@leadace.test)
#   GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET, OPENAI_API_KEY,
#   EMAILABLE_API_KEY, E2E_RECIPIENT_OVERRIDE
#                           copied into backend/.dev.vars when set. Set them on
#                           the cloud environment, never in the repo.

set -uo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

say() { printf '==> %s\n' "$*"; }
die() { printf 'cloud-bootstrap: %s\n' "$*" >&2; exit 1; }

# Both markers are documented; either one means a cloud session. This is
# accident protection, not authentication — it keeps the script from rewriting
# a developer's own backend/.dev.vars and frontend/.env.
if [ -z "${CLAUDE_CODE_REMOTE_SESSION_ID:-}" ] \
  && [ "${CLAUDE_CODE_REMOTE:-}" != "true" ] \
  && [ "${LEADACE_CLOUD_FORCE:-0}" != "1" ]; then
  die "not a cloud session, and this rewrites backend/.dev.vars and frontend/.env (LEADACE_CLOUD_FORCE=1 overrides)."
fi

# cloud-setup.sh installs node 24 under /usr/local; the image's own node
# (20/21/22) sits earlier on PATH.
if [ -x /usr/local/bin/node ] && /usr/local/bin/node --version | grep -q '^v24\.'; then
  PATH="/usr/local/bin:$PATH"
  export PATH
fi
say "node $(node --version), npm $(npm --version)"

supa() {
  if command -v supabase >/dev/null 2>&1; then supabase "$@"; else npx --yes supabase "$@"; fi
}

psql_local() {
  PGPASSWORD=postgres psql -h 127.0.0.1 -p 54322 -U postgres -d postgres -tAc "$1"
}

if ! docker info >/dev/null 2>&1; then
  say "Starting dockerd"
  (dockerd >/tmp/dockerd.log 2>&1 &)
  for _ in $(seq 1 60); do docker info >/dev/null 2>&1 && break; sleep 1; done
fi
docker info >/dev/null 2>&1 || die "docker is not reachable (see /tmp/dockerd.log)"

if supa status >/dev/null 2>&1; then
  say "Supabase already running"
else
  say "Starting Supabase (a cold image cache makes this slow)"
  supa start || die "supabase start failed"
fi

STATUS="$(supa status -o env 2>/dev/null)"
val() { printf '%s\n' "$STATUS" | grep -E "^$1=" | head -1 | cut -d= -f2- | tr -d '"'; }
SUPA_URL="$(val API_URL)"
DB_URL="$(val DB_URL)"
JWT_SECRET="$(val JWT_SECRET)"
ANON_KEY="$(val ANON_KEY)"
[ -n "$ANON_KEY" ] || ANON_KEY="$(val PUBLISHABLE_KEY)"
SERVICE_KEY="$(val SERVICE_ROLE_KEY)"
[ -n "$SERVICE_KEY" ] || SERVICE_KEY="$(val SECRET_KEY)"
require() { [ -n "$2" ] || die "supabase status reported no $1. Raw output:
$STATUS"; }
require API_URL "$SUPA_URL"
require DB_URL "$DB_URL"
require JWT_SECRET "$JWT_SECRET"
require ANON_KEY "$ANON_KEY"
require SERVICE_ROLE_KEY "$SERVICE_KEY"

GMAIL_KEY="$(openssl rand -hex 32)"
UNSUBSCRIBE_KEY="$(openssl rand -hex 32)"
[ -n "$GMAIL_KEY" ] && [ -n "$UNSUBSCRIBE_KEY" ] || die "openssl rand produced nothing"

# APP_URL is localhost here, which the send path refuses as an opt-out link
# host unless a recipient override is set (assertPublicHttpsSendHosts). Nothing
# can actually be sent from the VM — there is no Gmail identity — so the
# default is a sink address that keeps the draft and inquiry suites green.
E2E_SINK="${E2E_RECIPIENT_OVERRIDE:-e2e-sink@leadace.test}"

write_dev_vars() {
  cat > backend/.dev.vars <<EOF
# Generated by scripts/cloud-bootstrap.sh. Local-stack values only: the secrets
# are throwaway and the API keys come from the cloud environment's variables.
DATABASE_URL="$DB_URL"
APP_URL="http://localhost:5273"
WEB_API_URL="http://localhost:8787"
FRONTEND_URL="http://localhost:5273"
SUPABASE_JWT_SECRET="$JWT_SECRET"
SUPABASE_URL="$SUPA_URL"
SUPABASE_ANON_KEY="$ANON_KEY"
SUPABASE_SERVICE_ROLE_KEY="$SERVICE_KEY"
ENVIRONMENT="development"
LEADACE_EDITION="self-hosted"
GMAIL_TOKEN_ENCRYPTION_KEY="$GMAIL_KEY"
UNSUBSCRIBE_TOKEN_SECRET="$UNSUBSCRIBE_KEY"
GOOGLE_CLIENT_ID="${GOOGLE_CLIENT_ID:-}"
GOOGLE_CLIENT_SECRET="${GOOGLE_CLIENT_SECRET:-}"
OPENAI_API_KEY="${OPENAI_API_KEY:-}"
EMAILABLE_API_KEY="${EMAILABLE_API_KEY:-}"
E2E_RECIPIENT_OVERRIDE="$E2E_SINK"
EOF
}

write_frontend_env() {
  cat > frontend/.env <<EOF
# Generated by scripts/cloud-bootstrap.sh.
PUBLIC_API_URL=http://localhost:8787
PUBLIC_MCP_URL=http://localhost:8788
PUBLIC_SUPABASE_URL=$SUPA_URL
PUBLIC_SUPABASE_ANON_KEY=$ANON_KEY
PUBLIC_LEADACE_EDITION=self-hosted
EOF
}

if [ -f backend/.dev.vars ] && [ "${LEADACE_CLOUD_REGEN:-0}" != "1" ]; then
  say "backend/.dev.vars kept as is (LEADACE_CLOUD_REGEN=1 rewrites it)"
else
  write_dev_vars || die "could not write backend/.dev.vars"
  say "backend/.dev.vars written"
fi

if [ -f frontend/.env ] && [ "${LEADACE_CLOUD_REGEN:-0}" != "1" ]; then
  say "frontend/.env kept as is (LEADACE_CLOUD_REGEN=1 rewrites it)"
else
  write_frontend_env || die "could not write frontend/.env"
  say "frontend/.env written"
fi

for pkg in backend frontend; do
  if [ ! -d "$pkg/node_modules" ]; then
    say "npm ci ($pkg)"
    npm --prefix "$pkg" ci || die "npm ci failed in $pkg"
  fi
done

say "Applying migrations"
npm --prefix backend run db:migrate || die "migrations failed"
say "Seeding master documents"
npm --prefix backend run db:seed-master-documents || die "master-document seed failed"

# mint-jwt.sh signs for an existing auth.users row, whose tenant the auth.users
# trigger creates. Real sign-in needs Google OAuth in a browser, which a cloud
# session cannot drive, so provision the user through the GoTrue Admin API.
DEV_EMAIL="${LEADACE_DEV_EMAIL:-dev@leadace.test}"
case "$DEV_EMAIL" in
  *[!a-zA-Z0-9._%+@-]* | '') die "LEADACE_DEV_EMAIL must be a plain email address: $DEV_EMAIL" ;;
esac
USER_ID="$(psql_local "SELECT id FROM auth.users WHERE email = '$DEV_EMAIL' LIMIT 1;" 2>/dev/null | tr -d '[:space:]')"
if [ -z "$USER_ID" ]; then
  say "Creating dev user $DEV_EMAIL"
  created="$(curl -sS -X POST "$SUPA_URL/auth/v1/admin/users" \
    -H "Authorization: Bearer $SERVICE_KEY" -H "apikey: $SERVICE_KEY" \
    -H 'Content-Type: application/json' \
    -d "$(jq -nc --arg e "$DEV_EMAIL" --arg p "$(openssl rand -hex 16)" '{email:$e, email_confirm:true, password:$p}')")"
  USER_ID="$(printf '%s' "$created" | jq -r '.id // ""')"
  [ -n "$USER_ID" ] || die "could not create the dev user: $created"
fi
TENANT_ID="$(psql_local "SELECT tenant_id FROM tenant_members WHERE user_id = '$USER_ID' LIMIT 1;" | tr -d '[:space:]')"
[ -n "$TENANT_ID" ] || die "no tenant for $DEV_EMAIL — the auth.users trigger should have created one"

cat <<EOF

Stack ready.
  Supabase    $SUPA_URL
  Postgres    $DB_URL
  dev tenant  $TENANT_ID ($DEV_EMAIL)

Next:
  nohup make dev >/tmp/leadace-dev.log 2>&1 &   # API :8787, MCP :8788, frontend :5273
  ./e2e/regression-all.sh                       # curl-only suites
  cd backend && npm run typecheck && npm test
  cd frontend && npm run check
EOF
