#!/usr/bin/env bash
#
# Run a local Supabase stack with an overridable project id and host ports,
# without editing the tracked supabase/config.toml.
#
# Why this exists: `supabase start` reads supabase/config.toml, where the
# project id and ports are literals. The CLI's env() interpolation has no
# default-value syntax (an unset var leaves the literal "env(VAR)" in place,
# which then fails integer port decoding), so we cannot simply env()-ify the
# committed config without breaking the no-env path that normal dev / E2E / CI
# rely on. Instead this wrapper copies the config into a gitignored workdir,
# rewrites the project id + ports there, and runs the CLI with --workdir. The
# committed config is never touched.
#
# Usage:
#   scripts/supabase-local.sh start            # plain passthrough — identical
#                                              # to `npx supabase start`
#
#   SUPABASE_PROJECT_ID=leadace-oss \
#     scripts/supabase-local.sh start          # isolated stack: separate
#                                              # containers + DB volume, so it
#                                              # never touches the default
#                                              # `lead-ace` DB (e.g. the E2E one)
#
#   SUPABASE_PROJECT_ID=leadace-oss \
#   SUPABASE_PORT_OFFSET=100 \
#     scripts/supabase-local.sh start          # ...and shift every host port by
#                                              # 100 so it can run ALONGSIDE the
#                                              # default stack without clashing
#
#   SUPABASE_PROJECT_ID=leadace-oss \
#     scripts/supabase-local.sh status         # any subcommand is forwarded;
#     scripts/supabase-local.sh stop           # pass the same env so the CLI
#                                              # targets the same workdir
#
# Read the connection URL/keys it prints from `... status` into the gitignored
# backend/.dev.vars and frontend/.env — those already drive the API/MCP Workers
# and the frontend at the isolated ports.
#
# Behaviour:
#   - SUPABASE_PROJECT_ID unset  -> pure passthrough (no copy, no --workdir).
#   - SUPABASE_PROJECT_ID set    -> isolate into .supabase-local/<id>/.
#   - SUPABASE_PORT_OFFSET        -> integer added to every uncommented
#                                    port / shadow_port / inspector_port
#                                    (default 0). Only meaningful with an id.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"

if [ -z "${SUPABASE_PROJECT_ID:-}" ]; then
  exec npx supabase "$@"
fi

PROJECT_ID="$SUPABASE_PROJECT_ID"
OFFSET="${SUPABASE_PORT_OFFSET:-0}"

# The id becomes a path component (.supabase-local/<id>/) and a Docker object
# name, so constrain it: reject slashes / .. (which would escape the workdir on
# the rm -rf / cp below) and anything Docker would reject anyway.
if ! printf '%s' "$PROJECT_ID" | grep -Eq '^[A-Za-z0-9][A-Za-z0-9_-]*$'; then
  echo "supabase-local: SUPABASE_PROJECT_ID must match [A-Za-z0-9][A-Za-z0-9_-]*, got '$PROJECT_ID'" >&2
  exit 1
fi

if ! printf '%s' "$OFFSET" | grep -Eq '^-?[0-9]+$'; then
  echo "supabase-local: SUPABASE_PORT_OFFSET must be an integer, got '$OFFSET'" >&2
  exit 1
fi

WORKDIR="$REPO_ROOT/.supabase-local/$PROJECT_ID"
SRC="$REPO_ROOT/supabase"
DST="$WORKDIR/supabase"

# Rebuild the workdir's supabase dir from the committed source every run, so it
# always reflects the current config.toml + templates. Runtime state
# (.branches/.temp) is regenerated by the CLI and is not copied.
mkdir -p "$DST"
[ -d "$DST/templates" ] && rm -rf "$DST/templates"
[ -d "$SRC/templates" ] && cp -R "$SRC/templates" "$DST/templates"

# content_path/seed paths in config.toml are resolved relative to the workdir
# root, hence the copied supabase/ subtree.
awk -v pid="$PROJECT_ID" -v off="$OFFSET" '
  /^project_id = / { print "project_id = \"" pid "\""; next }
  /^(port|shadow_port|inspector_port) = [0-9]+$/ {
    key = $1
    print key " = " ($3 + off)
    next
  }
  { print }
' "$SRC/config.toml" > "$DST/config.toml"

echo "supabase-local: project '$PROJECT_ID', port offset $OFFSET, workdir $WORKDIR" >&2
# --workdir is a global flag; pass it before the subcommand so arg parsing of
# the forwarded "$@" can't swallow it.
exec npx supabase --workdir "$WORKDIR" "$@"
